### PR TITLE
Updated links to the right TestStack URL

### PR DESCRIPTION
**Pull request by cmatskas**
As per the title, simple change

### CODE REVIEW

**Comment by cmatskas** [comment]
This links to issue #220

**Comment by cmatskas** [comment]
Hello, did anyone get a chance to look into this? /cc @mwhelan @kkozmic @liammclennan

**Comment by JakeGinnivan** [comment]
My plan is to switch BDDfy over to readthedocs over the break, which is why I haven't done this.

**Comment by JakeGinnivan** [comment]
But can't hurt to merge for now :)

**Comment by cmatskas** [comment]
Awesome! Thanks ;)

Sent from Outlook Mobile




On Mon, Dec 14, 2015 at 4:37 PM -0800, "Jake Ginnivan" <notifications@github.com> wrote:












But can't hurt to merge for now :)

**Comment by mwhelan** [comment]
@JakeGinnivan I'd like to help with the doco move to ReadTheDocs. I should have a bit more free time next week. Let's coordinate over email.

**Comment by cmatskas** [comment]
I could put some time as well, if you need help?

**Comment by cmatskas** [comment]
Are we safe to close this one?

**Pull request merged**
