### PR TITLE
https://github.com/TestStack/TestStack.BDDfy/issues/216

### PR DESCRIPTION
**Pull request by wmekal**
Fixed null reference exception, which occurs when running tests in DNX.

### CODE REVIEW

**Comment by wmekal** [comment]
I haven't digged much into the code, so I don't know if it can have any negative impact.
I've just made a simple fix and I was able to run BDDfy tests in DNX.

**Comment by JakeGinnivan** [comment]
I am going to dig into dnx support over the break, will be another week or two

**Comment by JakeGinnivan** [comment]
Proper netstandard support is coming very soon. Gathering this is not actually needed anymore

**Comment by JakeGinnivan** [comment]
Thanks for the PR though, sorry about not just pulling in and releasing to unblock you.

**Pull request closed without merging**
