### PR TITLE
Corrected summary formatting problems

### PR DESCRIPTION
**Pull request by ByteBlast**
@mwhelan asked me to have a look at this. I managed to correct the alignment problems across modern web browsers.

This is what the summary looked like as of commit `fe1217`

This is what the summary looks like now

According to @mwhelan the approval tests are in a state of disarray right now. I _think_ I need to update the `*approved.txt` files to include the updated (minified) css. What is the best (automated?) way of doing this?

### CODE REVIEW

**Comment by mwhelan** [comment]
Well, I don't know if I would quite say they were in disarray but yeah, they are failing when you download the source from github. :-) 

Great work @ByteBlast ! Huge improvement and thanks for investigating and fixing the issue. It looks **so** much better! Just to be really pedantic, I wonder if it is possible for the numbers to be right aligned?

**Comment by ByteBlast** [comment]
Sorry. I used the wrong word :sheep: 

Hm. I do not know how to achieve that in this context off-hand. I mean, I _can_ get it to work



```css
.summaryCount {
    position: absolute;
    width: 30px;
    text-align: right;
}
```

but it involves setting a _fixed width_. Settings a fixed width disturbs the original layout a little bit and will cause breakage when the number needs more space than I defined. I would need to do some more research. Shall we revisit this at a future date if you still deem it important?

**Comment by mwhelan** [comment]
I think right alignment is quite important for numbers and the new screenshot looks a lot better. If it can support 4 digits then it should be fine?

**Comment by ByteBlast** [comment]
I think it is quite reasonable to accommodate 4 digits only. Hold on.

In the mean time could you please answer this question?

> I think I need to update the *approved.txt files to include the updated (minified) css. What is the best (automated?) way of doing this?

Must I update the `*approved.txt` files?

**Comment by mwhelan** [comment]
No, in fact I don't think you should as the file location seems to be dynamic depending on your local file location. I just meant that you can do that if  you want to get the tests passing, which you would if you are making changes to the report and using those tests to verify the changes. I think @JakeGinnivan and @MehdiK will have more idea than me about the cause of those tests failing and the best solution, so don't worry about it yourself.

**Comment by mwhelan** [comment]
Sorry, I've only partially answered your question, but the same applies. Wait for @MehdiK  or @JakeGinnivan to weigh in, as I'm not too sure about approval tests.

**Comment by ByteBlast** [comment]
> I just meant that you can do that if you want to get the tests passing

I understood that much :confused:. The `*approved.txt` files contain the now-unmodified CSS. I think the CSS in those files needs to be updated is all.  

Anyhoo, this is what the summary looks like now



If you exceed 4 digits then the formatting will break, like I said it would



What do you think?

**Comment by ByteBlast** [comment]
Many thanks for your guidance by the way.

**Comment by mwhelan** [comment]
Yes, I think you are probably right that the CSS needs to be modified in the approved file. So, you should go ahead and change that in the approved file. (I would say to approve the received file but the file location won't match the build server so in this case probably just change the CSS in the approved file).

I really like what you've done and I think we should go ahead with the change. I think it's very unlikely we would need more than four digits, but if the unlikely does happen, it actually still looks pretty good with the broken formatting.

**Comment by ByteBlast** [comment]
Done.

**Comment by mwhelan** [comment]
Thanks @ByteBlast for a valuable contribution and for persisting with getting it just right.

**Comment by ByteBlast** [comment]
No problem mate.

**Pull request merged**
